shim-version: v0.4.0@sha256:86e5fe4bcbf673847322c7416d49580ba6e8b41e30166fe9b8a8512b4a90c7ee
cvm-version: 0.6.7
cpus: 16
memory: 65536

containers:
  - name: "doc-upload"
    image: "ghcr.io/docling-project/docling-serve-cu130:v1.13.1@sha256:df1884e71573e36401eaedff6abbec875e026e522ac0e0e9854c77ee036e4df6"
    runtime: nvidia
    gpus: all

shim:
  listen-port: 443
  upstream-port: 5001
  authenticated: true
  paths:
    - /health
    - /v1/convert/file
